export const cropData = [
  {
    name: 'Beet',
    id: 'Beet',
    type: 'year round crop',
    maturityTime: 50,
    successionInterval: 14,
  },
  {
    name: 'Carrot',
    type: 'year round crop',
    maturityTime: 65,
    successionInterval: 14,
    id: 'Carrot',
  },
  {
    name: 'Collard',
    type: 'year round crop',
    maturityTime: 60,
    successionInterval: 21,
    id: 'Collard',
  },
  {
    name: 'Kale',
    type: 'year round crop',
    maturityTime: 60,
    successionInterval: 21,
    id: 'Kale',
  },
  {
    name: 'Chard',
    type: 'year round crop',
    maturityTime: 45,
    successionInterval: 14,
    id: 'Chard',
  },
  {
    name: 'Lettuce (Full Size)',
    type: 'year round crop',
    maturityTime: 55,
    successionInterval: 14,
    id: 'Lettuce (Full Size)',
  },
  {
    name: 'Lettuce (Salad)',
    type: 'year round crop',
    maturityTime: 28,
    successionInterval: 7,
    id: 'Lettuce (Salad)',
  },
  {
    name: 'Cilantro',
    type: 'year round crop',
    maturityTime: 35,
    successionInterval: 14,
    id: 'Cilantro',
  },
  {
    name: 'Radish',
    type: 'year round crop',
    maturityTime: 25,
    successionInterval: 7,
    id: 'Radish',
  },
  {
    name: 'Beans',
    type: 'warm season crop',
    maturityTime: 70,
    successionInterval: 14,
    id: 'Beans',
  },
  {
    name: 'Basil',
    type: 'warm season crop',
    maturityTime: 68,
    successionInterval: 14,
    id: 'Basil',
  },
  {
    name: 'Genovese',
    type: 'warm season crop',
    maturityTime: 68,
    successionInterval: 14,
    id: 'Genovese',
  },
  {
    name: 'Corn',
    type: 'warm season crop',
    maturityTime: 65,
    successionInterval: 14,
    id: 'Corn',
  },
  {
    name: 'Cucumber',
    type: 'warm season crop',
    maturityTime: 68,
    successionInterval: 21,
    id: 'Cucumber',
  },
  {
    name: 'Dill',
    type: 'warm season crop',
    maturityTime: 50,
    successionInterval: 14,
    id: 'Dill',
  },
  {
    name: 'Eggplant',
    type: 'warm season crop',
    maturityTime: 90,
    successionInterval: 14,
    id: 'Eggplant',
  },
  {
    name: 'Okra',
    type: 'warm season crop',
    maturityTime: 56,
    successionInterval: 14,
    id: 'Okra',
  },
  {
    name: 'Pepper',
    type: 'warm season crop',
    maturityTime: 75,
    successionInterval: 14,
    id: 'Pepper',
  },
  {
    name: 'Pumpkin',
    type: 'warm season crop',
    maturityTime: 105,
    successionInterval: 28,
    id: 'Pumpkin',
  },
  {
    name: 'Summer Squash',
    type: 'warm season crop',
    maturityTime: 70,
    successionInterval: 14,
    id: 'Summer Squash',
  },
  {
    name: 'Cauliflower',
    type: 'cool season crop',
    maturityTime: 70,
    successionInterval: 14,
    id: 'Cauliflower',
  },
  {
    name: 'Broccoli',
    type: 'cool season crop',
    maturityTime: 70,
    successionInterval: 14,
    id: 'Broccoli',
  },
  {
    name: 'Peas',
    type: 'cool season crop',
    maturityTime: 75,
    successionInterval: 14,
    id: 'Peas',
  },
  {
    name: 'Cabbage',
    type: 'cool season crop',
    maturityTime: 100,
    successionInterval: 14,
    id: 'Cabbage',
  },
];
